package com.pojo;
// Generated Apr 11, 2018 3:35:56 PM by Hibernate Tools 4.3.1



/**
 * Login generated by hbm2java
 */
public class Login  implements java.io.Serializable {


     private int id;
     private String name;
     private String email;
     private String password;

    public Login() {
    }

	
    public Login(int id) {
        this.id = id;
    }
    public Login(int id, String name, String email, String password) {
       this.id = id;
       this.name = name;
       this.email = email;
       this.password = password;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


